export const rowData = [{
    'BusinessCode': 'test-data-1',
    'Market_Country': 'test-data-2',
    'Document_Item_Currency': 'test-data-3',
    'Amount': 'test-data-4',
    'Currency': 'test-data-5',
    'Delivering_Mill': 'test-data-6',
    'Product_Division': 'test-data-7',
    'Market_Customer': 'test-data-8',
    'Market_Customer_Group': 'test-data-9',
    'Grade_Category': 'test-data-10',
    'Product_Level_02': 'test-data-11',
    'Product_Level_04': 'test-data-12',
    'Product_Level_05': 'test-data-13',
    'Transport_Mode': 'test-data-14',
    'Length': 'test-data-15',
    'Country_Group': 'test-data-16',
    'Zip_Code_Dest': 'test-data-17',
    'Certificate': 'test-data-20',
    'Beam_Category': 'test-data-21',
    "id_value": 12
}]